### ISSUE TITLE
What are valid type of logs & TTP file

### ISSUE THREAD

**Issue by Llugway** [Patrick-DE/Cobaltstrike-logparser#2]
Hi,

I'm questioning me about what type of log files are accepted by CobaltStrike-logparser ?

When i launch the script, my files in log files are ignored (.json, .csv and .log).

And how i can found a valid TTP (Tactics, techniques and procedures ?) config file ?

Ty for your answer.

**Comment by Patrick-DE** [comment]
If you use cobalt strike, there is a folder being created called logs or so. The path to this folder should be provided.
Which version of CS are you using?
For the TTPs, you need to provide a csv file mapping strings, used as detection, to their respective TTPs.
That means, the mapping needs to be done by yourself.
I will post a sample file in the next days as a reference.

**Comment by Llugway** [comment]
Ok ty for your answer !
I'm waiting for your sample file :)

**Comment by Patrick-DE** [comment]
Added the ttp.csv file. Feel free to add some TTPs if you want.
